# Generated by Django 5.2.3 on 2025-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.JSONField(default=dict)),
                ('contact', models.JSONField(default=dict)),
            ],
        ),
    ]
