# Generated by Django 5.2.3 on 2025-07-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='prj_git_url',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
