# Generated by Django 5.2.3 on 2025-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_projects_prj_git_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
