# Generated by Django 5.2.3 on 2025-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_projects_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
