# Generated by Django 5.2.4 on 2025-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_projects_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='contact',
        ),
        migrations.AddField(
            model_name='about',
            name='git_link',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
